# Dockerfile creating Ubuntu 16.04 with Tensorflow 0.11
# Also adds in some dot files for development
FROM fbcotter/tensorflow

MAINTAINER Fergal Cotter <fbc23@cam.ac.uk>

RUN apt-get update
RUN apt-get -qq update

# Add some developer tools
RUN apt-get -qq install -y man vim 
ADD dotfiles/vimrc /root/.vimrc
RUN mkdir -p /root/.vim/bundle 
WORKDIR /root/.vim/bundle
ADD dotfiles/bash_profile /root/.bash_profile
ADD dotfiles/bash_prompt /root/.bash_prompt
# install vim plugins&& cd /root/.vim/bundle
RUN git clone --depth 1 https://github.com/gmarik/Vundle.vim.git                && \ 
    git clone --depth 1 https://github.com/altercation/vim-colors-solarized.git && \
    git clone --depth 1 https://github.com/scrooloose/syntastic.git              && \
    git clone --depth 1 https://github.com/scrooloose/nerdcommenter.git          && \
    git clone --depth 1 https://github.com/scrooloose/nerdtree.git               && \
    git clone --depth 1 https://github.com/MattesGroeger/vim-bookmarks.git      && \
    git clone --depth 1 https://github.com/vim-airline/vim-airline.git          && \
    git clone --depth 1 https://github.com/vim-airline/vim-airline-themes.git   
RUN echo | echo | vim +PluginInstall +qall  &> /dev/null
RUN mkdir /root/.jupyter
ADD dotfiles/jupyter_config /root/.jupyter

VOLUME ["/data", "/exps"]
ENV TERM xterm-256color
WORKDIR /root
EXPOSE 8888
EXPOSE 6006

CMD ["/bin/bash", "-l"]


